language: go

sudo: false

go:
  - 1.6.x
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - master

before_install:
  - go get github.com/stretchr/testify/assert

install:
  - go get github.com/alecthomas/gometalinter
  - gometalinter --install --vendored-linters

script:
  - gometalinter --config=gometalinter.json --deadline=10m
  - go test -race -v -bench=.
