language: go

sudo: false

go:
  - 1.10.x
  - 1.11.x
  - master

before_install:
  - curl -L https://git.io/vp6lP | sh
  - go get github.com/stretchr/testify/assert

script:
  - gometalinter --config=gometalinter.json --deadline=10m
  - go test -race -v -bench=.
